### PR TITLE
style: apply black formatting

### PR DESCRIPTION
**Pull request by redeboer**
This is a proposal presented as a PR (instead of an issue) as to be able to directly see the effect. The formatting is also tested in Travis CI.

See also https://github.com/ComPWA/tensorwaves/pull/49

### CODE REVIEW

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 12
- Added 198
           

Clones added
============
- tests/unittests/ui/test_systemcontrol.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5434605&bid=17821373)

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 12
- Added 198
           

Clones added
============
- tests/unittests/ui/test_systemcontrol.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5434605&bid=17821373)

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 12
- Added 87
           

Clones added
============
- tests/unittests/ui/test_systemcontrol.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5434605&bid=17821373)

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 12
- Added 85
           

Clones added
============
- tests/unittests/ui/test_systemcontrol.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5434605&bid=17821373)

**Comment by spflueger** [comment]
Its a good idea, but I don't think we need to bring this into pycompwa now (since we want to move to tensorwaves)

**Comment by redeboer** [comment]
Yes that's correct, this PR has been moved to tensorwaves https://github.com/ComPWA/tensorwaves/pull/50

**Comment by redeboer** [comment]
Yes that's correct, this PR has been moved to tensorwaves https://github.com/ComPWA/tensorwaves/pull/50

**Pull request closed without merging**
