### PR TITLE
docs: improve rendering of typing hints in API

### PR DESCRIPTION
**Pull request by redeboer**

### CODE REVIEW

**Comment by redeboer** [comment]
See also https://github.com/ComPWA/tensorwaves/pull/47

**Comment by spflueger** [comment]
This looks good to me. Do you want to make this into a normal PR?

**Comment by redeboer** [comment]
Okay removed draft status, was just there because I wanted to see how tensorwaves developed with regard to these type hints

**Comment by redeboer** [comment]
Better to revisit the dev setup of this repo after https://github.com/ComPWA/tensorwaves/issues/78. But okay, let's not focus on pycompwa.

**Pull request merged**
