### PR TITLE
docs: move workflow and tools pages up

### PR DESCRIPTION
**Pull request by redeboer**
The table of contents in the index has become rather large (because the depth is 3). In contrast, the side bar has become rather small. So given that the usage page itself did not contribute much, the two pages it referred to (tools and workflow) have been moved up.

old: https://compwa.github.io
new: https://redeboer.github.io/testpages

### CODE REVIEW

**Comment by redeboer** [comment]
> Looks still a little bit long.

Yes that's right. Although the "new" also includes other branches that is being worked on, like the theory and the contribute tutorials.

> Is it possible to move some part of the table of contents to the right?

But yes, this might be a good idea when those other branches are also integrated and the TOC becomes longer. Maybe one can play around with the `:hidden:` flag in the [`toctree` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#table-of-contents). That's [already happening with the `api`](https://raw.githubusercontent.com/ComPWA/pycompwa/master/doc/source/index.rst). But well, worry for later.

**Comment by spflueger** [comment]
Hmm, from the above comment I do not understand what the PR is supposed to achieve. So I think this should be an issue first. Then we can discuss what is bad and how to improve it. Once that's clear you can make a PR for it.

**Comment by redeboer** [comment]
Actually it comes from working on https://github.com/ComPWA/pycompwa/issues/82. That one has several nested tutorial pages, which looks like a mess on the index page. I then noticed that the Usage section is a bit redundant.

In that sense, I'm not sure if there can be a strict boundary between PR and issue. And since the proposed change is small, I'd argue a direct PR that illustrates the idea is more efficient here.

**Comment by redeboer** [comment]
Put on halt since https://github.com/ComPWA/pycompwa/issues/82 has been scaled down / migrated to general PWA website

**Pull request closed without merging**
