### PR TITLE
docs: clean up sphinx documentation

### PR DESCRIPTION
**Pull request by redeboer**

### CODE REVIEW

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5222753&bid=17123601)

**Comment by redeboer** [comment]
Retry DeepCode

**Comment by redeboer** [comment]
Retry DeepCode

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5222753&bid=17123601)

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5222753&bid=17123601)

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5222753&bid=17123601)

**Comment by spflueger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ComPWA/pycompwa/pullRequest?prid=5222753&bid=17123601)

**Pull request merged**
